labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        **Please check the existing discussions first.**
  - type: textarea
    attributes:
      label: Idea
    validations:
      required: true
