blank_issues_enabled: false
contact_links:
  - name: Matrix room
    url: https://matrix.to/#/#tree-sitter-chat:matrix.org
    about: Chat or ask questions
  - name: Discord server
    url: https://discord.gg/w7nTvsVJhm
    about: Chat or ask questions
