name: Publish package (crates.io)

on:
  workflow_call:
    inputs:
      crate-name:
        type: string
        default: ${{github.event.repository.name}}
    secrets:
      CARGO_REGISTRY_TOKEN:
        required: true

jobs:
  rust:
    name: Publish Rust package
    runs-on: ubuntu-latest
    environment:
      name: crates
      url: https://crates.io/crates/${{inputs.crate-name}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Publish to crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_REGISTRY_TOKEN}}
