name: Fuzz parser

on:
  workflow_call:
    inputs:
      language:
        type: string
      directory:
        type: string
        default: .
      timeout:
        type: number
        default: 10
      time:
        type: number
        default: 60

jobs:
  fuzz:
    name: Parser fuzzing
    runs-on: ubuntu-latest
    steps:
      - run: printf '::notice::The fuzz workflow is deprecated. Use tree-sitter-fuzz-action instead.\n'
      - uses: actions/checkout@v4
      - uses: tree-sitter-grammars/tree-sitter-fuzz-action@v3
        with:
          directory: ${{inputs.directory}}
          timeout: ${{inputs.timeout}}
          max-time: ${{inputs.time}}
