name: Publish package (pypi)

on:
  workflow_call:
    inputs:
      project-name:
        type: string
        default: ${{github.event.repository.name}}
    secrets:
      # TODO: make optional when pypi/warehouse#11096 is fixed
      PYPI_API_TOKEN:
        required: true

jobs:
  build_wheels:
    name: Build on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16
        with:
          output-dir: dist
      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          path: dist/*.whl
          name: ${{matrix.os}}-wheels
          retention-days: 1

  upload_pypi:
    name: Upload wheels to PyPI
    needs: [build_wheels]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/${{inputs.project-name}}/
    # permissions:
    #   id-token: write
    steps:
      - name: Download wheel artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: "*-wheels"
          merge-multiple: true
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.8
        with:
          password: ${{secrets.PYPI_API_TOKEN}}
