name: Release

on:
  workflow_call:
    inputs:
      package-name:
        type: string
        default: ${{github.event.repository.name}}
      upload-artifacts:
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Publish release
    runs-on: ubuntu-latest
    if: github.ref_name == 'master'
    outputs:
      tag_name: ${{steps.release.outputs.tag_name}}
      release_created: ${{steps.release.outputs.release_created}}
    steps:
      - name: Publish release
        id: release
        # XXX: the package-name input is removed in v4
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: ${{inputs.package-name}}
  upload:
    name: Upload release artifacts
    runs-on: ubuntu-latest
    needs: [release]
    if: needs.release.outputs.release_created == 'true' && inputs.upload-artifacts == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{vars.NODE_VERSION}}
      - name: Set up Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{vars.EMSCRIPTEN_VERSION}}
      - name: Install dependencies
        run: npm install
      - name: Build WASM artifact
        run: node_modules/.bin/tree-sitter build-wasm
      - name: Upload WASM artifact
        run: gh release upload '${{needs.release.outputs.tag_name}}' *.wasm
        env:
          GITHUB_TOKEN: ${{github.token}}
